spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOSTNAME}:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: always
    hikari:
      pool-name: {{ cookiecutter.project_slug.title().replace('-', '') }}_hikari
      maximum-pool-size: 10
  jackson:
    serialization:
      write-dates-as-timestamps: false


  # validate the schema, no changes to the database
  # without it the application would start up even if the schema is not present
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

  # disable database initialisation with Spring JDBC, enabled by default
  flyway:
    enabled: true
    baseline-on-migrate: true