spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/{{ cookiecutter.package_name }}-db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mysqlpass
    initialization-mode: always
  jackson:
    serialization:
      write-dates-as-timestamps: false


  # validate the schema, no changes to the database
  # without it the application would start up even if the schema is not present
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

  # disable database initialisation with Spring JDBC, enabled by default
  flyway:
    enabled: true
    baseline-on-migrate: true