---
version: "3.3"

services:
  web:
    image: "${BUILDER_IMAGE:218894879100.dkr.ecr.us-east-1.amazonaws.com/{{ cookiecutter.group }}/{{ cookiecutter.project_slug }}/build:latest}"
    build:
      context: .
      dockerfile: build.Dockerfile
      args:
        - VERSION
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=test